{% set name = "gplearn" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/trevorstephens/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 0dbeecc9b648d26be6445fd3ac1d5744057faa67b26ce2369dbbd6df49560e74

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - scikit-learn >=0.22.1
    - joblib >=0.13.0

test:
  imports:
    - gplearn

about:
  home: https://github.com/trevorstephens/gplearn/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: gplearn implements Genetic Programming in Python, with a scikit-learn inspired and compatible API

  description: |
    gplearn is purposefully constrained to solving symbolic regression
    problems. gplearn retains the familiar scikit-learn fit/predict API
    and works with the existing scikit-learn pipeline and grid search modules.
    gplearn is built for Python 3.5+ and requires scikit-learn
  doc_url: https://gplearn.readthedocs.io/
  dev_url: https://github.com/trevorstephens/gplearn/

extra:
  recipe-maintainers:
    - owenlamont
